name: Minikube workflow
on: push
jobs:
  minikube:
    name: Start Kubernetes cluster
    runs-on: ubuntu-20.04
    steps:
      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@latest
        with:
          profile: github

      - name: Get Minikube status
        run: minikube status

      - name: Get cluster info
        run: kubectl cluster-info

      - name: Get Kubernetes pods
        run: kubectl get services --all-namespaces
        
      - name: Install wordpress
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm install app-wp1 bitnami/wordpress
          
      - name: Get Helm releases
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm list
